package com.yadda.integrate.provider.dao;

import com.yadda.integrate.model.AppUser;
import com.yadda.integrate.model.AppUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    long countByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int deleteByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int deleteByPrimaryKey(Integer fuserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int insert(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int insertSelective(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    List<AppUser> selectByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    AppUser selectByPrimaryKey(Integer fuserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppUser record, @Param("example") AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int updateByExample(@Param("record") AppUser record, @Param("example") AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int updateByPrimaryKeySelective(AppUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUser
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int updateByPrimaryKey(AppUser record);
}