package com.yadda.integrate.provider.dao;

import com.yadda.integrate.model.AppUserTemp;

public interface AppUserTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUserTemp
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUserTemp
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int insert(AppUserTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUserTemp
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int insertSelective(AppUserTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUserTemp
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    AppUserTemp selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUserTemp
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int updateByPrimaryKeySelective(AppUserTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AppUserTemp
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int updateByPrimaryKey(AppUserTemp record);
}