package com.yadda.integrate.provider.dao;

import com.yadda.integrate.model.SecurityResources;

public interface SecurityResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KS_SECURITYRESOURCES
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KS_SECURITYRESOURCES
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int insert(SecurityResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KS_SECURITYRESOURCES
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int insertSelective(SecurityResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KS_SECURITYRESOURCES
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    SecurityResources selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KS_SECURITYRESOURCES
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int updateByPrimaryKeySelective(SecurityResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KS_SECURITYRESOURCES
     *
     * @mbg.generated Tue Oct 11 12:42:32 CST 2016
     */
    int updateByPrimaryKey(SecurityResources record);
}